### ISSUE TITLE
Add 'Oida'

### ISSUE THREAD

**Issue by dnsmichi** [NETWAYS/icingaweb2-theme-oesterreichisch#2]
It is missing in the translation @widhalmt 

<img width="694" alt="Screenshot 2020-04-03 at 14 03 03" src="https://user-images.githubusercontent.com/382049/78358699-e9c7c280-75b3-11ea-84e3-4f5e2df0204b.png">

**Comment by widhalmt** [comment]
Oh yes! Thanks for the issue. Maybe you could issue a pull request? (I always wanted to tell this to you. :-D)

**Comment by dnsmichi** [comment]
I would have created a PR with changes, and avoided the issue. Unfortunately I lack the time to work with POEdit, or re-create a dev environment for Icinga. As you know, I have left the project and have therefore no further development environments or alike. That's why I have created the issue for you :-)

**Comment by widhalmt** [comment]
As always: PR's are better than issues. But issues a way better than no issues. So, thanks anyway. :-)

**Comment by dnsmichi** [comment]
This is the way. 🐸

**Comment by martialblog** [comment]
Closed due to inactivity. Can be reopened if necessary
